<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
   <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c0c3c9b5-6cd3-431a-8101-9366cf259fb9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlantWise.Application\PlantWise.Application.csproj" />
    <ProjectReference Include="..\PlantWise.Infrastructure\PlantWise.Infrastructure.csproj" />
    <ProjectReference Include="..\PlantWise.Shared\PlantWise.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

</Project>
